require_relative '../node_modules/expo/scripts/autolinking'

# Resolve react_native_pods.rb with node to allow for hoisting
require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    "react-native-permissions/scripts/setup.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip

platform :ios, '15.6'
install! 'cocoapods', :deterministic_uuids => false

linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end
$RNFirebaseAsStaticFramework = true

# Shared method to configure React Native
def configure_react_native(config)
  use_expo_modules!
  use_react_native!(
    :path => config[:reactNativePath],
    :fabric_enabled => true,
    :hermes_enabled => true,
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )
end

# Shared dependencies
def add_common_dependencies()
  pod 'Firebase', :modular_headers => true
  pod 'FirebaseCoreInternal', :modular_headers => true
  pod 'GoogleUtilities', :modular_headers => true
  pod 'FirebaseCore', :modular_headers => true
  permissions_path = '../node_modules/react-native-permissions/ios'
  pod 'Permission-Microphone', :path => "#{permissions_path}/Microphone"
  pod 'Permission-Camera', :path => "#{permissions_path}/Camera"
end

abstract_target '2060CommonPods' do
  target '2060Dev' do
   end

   target '2060Staging' do
   end

   target '2060Prod' do
   end
  config = use_native_modules!
  configure_react_native(config)
  post_integrate do |installer|
    begin
      expo_patch_react_imports!(installer)
    rescue => e
      Pod::UI.warn e
    end
  end
  add_common_dependencies()
  pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec', :modular_headers => false
  pre_install do |installer|
    Pod::Installer::Xcode::TargetValidator.send(:define_method, :verify_no_static_framework_transitive_dependencies) {}
  end

  post_install do |installer|
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false,
      # :ccache_enabled => true
    )
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= ['$(inherited)', '_LIBCPP_ENABLE_CXX17_REMOVED_UNARY_BINARY_FUNCTION']
        config.build_settings['APPLICATION_EXTENSION_API_ONLY'] = 'NO'
      end
    end
  end
end

abstract_target 'CommonShareExtensionPods' do
  config = use_native_modules!
  configure_react_native(config)
  add_common_dependencies()
  pod 'RNShareMenu', :path => '../node_modules/react-native-share-menu'

  target 'ShareExtensionDev' do
    # Additional configurations specific to ShareExtensionDev
  end
  target 'ShareExtensionStaging' do
    # Additional configurations specific to ShareExtensionStaging
  end
  target 'ShareExtensionProd' do
    # Additional configurations specific to ShareExtensionProd
  end
end