require File.join(File.dirname(`node --print "require.resolve('expo/package.json')"`), "scripts/autolinking")

def node_require(script)
  # Resolve script with node to allow for hoisting
  require Pod::Executable.execute_command('node', ['-p',
    "require.resolve(
      '#{script}',
      {paths: [process.argv[1]]},
    )", __dir__]).strip
end

# Use it to require both react-native's and this package's scripts:
node_require('react-native/scripts/react_native_pods.rb')
node_require('react-native-permissions/scripts/setup.rb')

platform :ios, '16.0'
install! 'cocoapods', :deterministic_uuids => false

linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end
$RNFirebaseAsStaticFramework = true

# Shared method to configure React Native
def configure_react_native(config)
  use_expo_modules!
  use_react_native!(
    :path => config[:reactNativePath],
    :fabric_enabled => true,
    :hermes_enabled => true,
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )
end

# Shared dependencies
def add_common_dependencies()
  pod 'Firebase', :modular_headers => true
  pod 'FirebaseCoreInternal', :modular_headers => true
  pod 'GoogleUtilities', :modular_headers => true
  pod 'FirebaseCore', :modular_headers => true
end

setup_permissions([
   'Camera',
   'Microphone',
])

abstract_target 'CommonPods' do
  target 'Dev' do
   end

   target 'Staging' do
   end

   target 'Prod' do
   end
  config = use_native_modules!
  configure_react_native(config)
  post_integrate do |installer|
    begin
      expo_patch_react_imports!(installer)
    rescue => e
      Pod::UI.warn e
    end
  end
  add_common_dependencies()
  # Match modular-header settings that use_expo_modules! enables in the share
  # extension abstract target, to avoid CocoaPods "Unable to determine whether
  # to build ... as a module" warnings.
  pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec', :modular_headers => true
  pod 'React-RCTAppDelegate', :path => "#{config[:reactNativePath]}/Libraries/AppDelegate", :modular_headers => true
  pre_install do |installer|
    Pod::Installer::Xcode::TargetValidator.send(:define_method, :verify_no_static_framework_transitive_dependencies) {}
  end

  post_install do |installer|
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false,
      :ccache_enabled => true
    )
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= ['$(inherited)', '_LIBCPP_ENABLE_CXX17_REMOVED_UNARY_BINARY_FUNCTION']
        config.build_settings['APPLICATION_EXTENSION_API_ONLY'] = 'NO'
      end
      if target.name == 'fmt'
        target.build_configurations.each do |config|
          config.build_settings['CLANG_CXX_LANGUAGE_STANDARD'] = 'c++17'
        end
      end
      if ['Expo', 'ExpoModulesCore'].include?(target.name)
        target.build_configurations.each do |config|
          config.build_settings['GCC_WARN_INHIBIT_ALL_WARNINGS'] = 'YES'
          config.build_settings['SWIFT_ENABLE_EXPLICIT_MODULES'] = 'NO'
        end
      end
    end
  end
end

abstract_target 'CommonShareExtensionPods' do
  use_expo_modules!
  use_react_native!
  pod 'RNShareMenu', :path => '../node_modules/react-native-share-menu'

  target 'ShareExtensionDev' do
    # Additional configurations specific to ShareExtensionDev
  end
  target 'ShareExtensionStaging' do
    # Additional configurations specific to ShareExtensionStaging
  end
  target 'ShareExtensionProd' do
    # Additional configurations specific to ShareExtensionProd
  end
end