name: Unstable release

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  release-please:
    runs-on: ubuntu-latest
    outputs:
      releases_created: ${{ steps.release-please.outputs.releases_created }}
      paths_released: ${{ steps.release-please.outputs.paths_released }}
    steps:
      - uses: googleapis/release-please-action@v4
        id: release-please
        with:
          manifest-file: .release-please-manifest.json
          config-file: unstable-release-config.json
          skip-github-release: true
          skip-github-pull-request: true
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Print release outputs for debugging
        continue-on-error: true
        run: |
          echo "Release outputs:"
          echo ${{ toJson(steps.release-please.outputs) }}